food_stories/api/urls.py
from django.urls import path
from api.views import recipes, recipe_detail, registration, CustomAuthToken, SubscriberAPIView
from rest_framework.authtoken.views import obtain_auth_token
from api.routers import router 

app_name = 'api'

urlpatterns = [
    path('recipes/', recipes, name='recipes'),
    path('recipes/<int:recipe_id>/', recipe_detail, name='recipe_detail'),
    path('register/', registration, name='registration'),
    path('subscribe/', SubscriberAPIView.as_view(), name='subscribe'),
    path('login/', CustomAuthToken.as_view(), name='api_login'),
] + router.urls

food_stories/food_stories/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include


urlpatterns = [
    path('jet/', include('jet.urls', 'jet')),  # Django JET URLS
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),  # Django JET dashboard URLS
    path('admin/', admin.site.urls),
    path('', include('social_django.urls', namespace='social')),
    path('', include('stories.urls')),
    path('api/v1.0/', include('api.urls', namespace='api')),
    path('accounts/', include('accounts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_stories/stories/urls.py
from django.urls import path
from stories.views import test, ContactView, RecipeList, RecipeDetail, AboutView, \
        StoryList, dump, SubscribeView, Home, UserProfile, CreateStory, CreateRecipe, RecipeUpdateView, \
        RecipeDeleteView


urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('about/', AboutView.as_view(), name='about'),
    path('test/', test, name='test'),
    path('recipes/', RecipeList.as_view(), name="recipes"),
    path('create-story/', CreateStory.as_view(), name="create_story"),
    path('create-recipe/', CreateRecipe.as_view(), name="create_recipe"),
    path('update-recipe/<int:pk>/', RecipeUpdateView.as_view(), name="update_recipe"),
    path('delete-recipe/<int:pk>/', RecipeDeleteView.as_view(), name="delete_recipe"),
    path('stories/', StoryList.as_view(), name="stories"),
    path('recipe-detail/<int:pk>/', RecipeDetail.as_view(), name="recipe-detail"),
    path('contact/', ContactView.as_view(), name='contact'),
    path('dump/', dump, name='dump'),
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),
    path('user-profile/', UserProfile.as_view(), name='user-profile'),
]

food_stories/stories/models.py
import math
from django.db import models
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField
from django.urls import reverse_lazy

User = get_user_model()

# class Author(models.Model):
#     full_name = models.CharField('Tam Adı', max_length=60)
#     description = models.TextField()
#     image = models.ImageField(upload_to="media/authors/")

#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

#     class Meta:
#         verbose_name = 'Müəllif'
#         verbose_name_plural = 'Müəlliflər'
    
#     def __str__(self):
#         return self.full_name


class Tag(models.Model):
    title = models.CharField('Title', max_length=20)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Tag'
        verbose_name_plural = 'Tags'

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField('Title', max_length=50)
    image = models.ImageField('Şəkil', upload_to="categories/")

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Kateqoriya'
        verbose_name_plural = 'Kateqoriyalar'

    def __str__(self):
        return self.title


class Recipe(models.Model):
    # relations
    tags = models.ManyToManyField(Tag, related_name='recipes')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    #information
    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='recipes/')
    short_description = models.TextField(max_length=1000, help_text="bu reseptler siyahisinda cixacaq metindir")
    long_description = RichTextField(null=True, blank=True)
    min_read_time = models.PositiveIntegerField("Min read time", editable=False)

    # moderation
    is_published = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "recipes"
        verbose_name = "Resept"
        verbose_name_plural = "Reseptlər"
        ordering = 'created_at',

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        length_long_desc = len(self.long_description.split(' '))
        min_read_sec = length_long_desc/2
        self.min_read_time = math.ceil(min_read_sec/60)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse_lazy('recipe-detail', kwargs={'pk': self.id})


class Story(models.Model):
    tags = models.ManyToManyField(Tag, related_name='stories')

    title = models.CharField(max_length=255)
    image = models.ImageField(upload_to='recipes/')
    long_description = RichTextField(null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    min_read_time = models.PositiveIntegerField("Min read time", editable=False, null=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        # db_table = "stories"
        verbose_name = "Hekaye"
        verbose_name_plural = "Hekayeler"
        ordering = 'created_at',

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        length_long_desc = len(self.long_description.split(' '))
        min_read_sec = length_long_desc/2
        self.min_read_time = math.ceil(min_read_sec/60)
        super().save(*args, **kwargs)
    
    # To do make story detail page
    # def get_absolute_url(self):
    #     return reverse_lazy('recipe-detail', kwargs={'pk': self.id})


class Contact(models.Model):
    user_name = models.CharField('User name', max_length=50)
    user_email = models.EmailField('User email', max_length=50)
    subject = models.CharField('Subject', max_length=255)
    message = models.TextField('Message')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Contact"
        verbose_name_plural = "Contacts"
    
    def __str__(self):
        return self.user_name


class About(models.Model):
    title = models.CharField('Title', max_length=50)
    phone_number = models.CharField('Phone Number', max_length=20)
    location = models.CharField('Location', max_length=50)
    email = models.EmailField('Email', max_length=30)
    description = models.TextField('Description')
    daily_visitors = models.PositiveIntegerField('Daile Visitors',)
    facebook_page_url = models.URLField('Facebook page url')
    instagram_page_url = models.URLField('Instagram page url')
    twitter_page_url = models.URLField('Twitter page url')

    class Meta:
        verbose_name = 'About Site Information'
        verbose_name_plural = 'About Site Informations'
    
    def __str__(self):
        return self.title

    
class Subscriber(models.Model):
    #informations
    email = models.EmailField('Email', max_length=30, unique=True)

    # moderations
    is_active = models.BooleanField('is_active', default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Subscriber"
        verbose_name_plural = "Subscribers"
    
    def __str__(self):
        return self.email


class Comment(models.Model):
    # relation's
    user = models.ForeignKey(User, related_name='comments', on_delete=models.CASCADE)
    parent_comment = models.ForeignKey('self', related_name='sub_comments', on_delete=models.CASCADE, null=True, blank=True)
    recipe = models.ForeignKey(Recipe, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)
    story = models.ForeignKey(Story, related_name='comments', on_delete=models.CASCADE, null=True, blank=True)

    #information's
    comment_msg = models.TextField('Comment', )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "Comment"
        verbose_name_plural = "Comments"
    
    def __str__(self):
        return self.user.get_full_name()

food_stories/stories/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView, ListView, DetailView, TemplateView, \
    UpdateView, DeleteView
from django.views.generic.edit import FormMixin
from datetime import date
from stories.models import Recipe, Story, Category, Comment
from stories.forms import ContactForm, SubscriberForm, StoryForm, RecipeForm, CommentForm
from django.contrib import messages
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin



# def home(request):
#     return render(request, 'index.html')

class Home(TemplateView):
    template_name = 'index.html'

# def about(request):
#     return render(request, 'about.html')


class AboutView(TemplateView):
    template_name = 'about.html'


def test(request):
    message = 'Lorem ipsum dolor sit, amet consectetur adipisicing elit. Ea illo aliquam cumque, eum animi repudiandae nostrum optio quisquam, distinctio magni, impedit reiciendis similique ab! Reiciendis atque reprehenderit asperiores debitis laboriosam.'
    html_context = "<h1> Salam Dunya</h1>"
    new_date = date(2018, 3, 1)
    a = [1,2,3,4,5,6]
    context = {
        'pi': 3.1457,
        'msg': message,
        'new_date': new_date,
        'html_context': html_context,
        'a': a,
    }
    return render(request, 'test.html', context)


# def recipes(request):
#     recipe_list = Recipe.objects.all()
#     context = {
#         'recipes': recipe_list
#     }
#     return render(request, 'recipes.html', context)


class RecipeList(ListView):
    model = Recipe
    template_name = 'recipes.html'
    context_object_name = 'recipes'
    paginate_by = 2


class StoryList(ListView):
    model = Story
    template_name = 'stories.html'
    # context_object_name = 'recipes'
    paginate_by = 2


class RecipeDetail(FormMixin, DetailView):
    model = Recipe
    form_class = CommentForm
    template_name = 'single.html'

    def get_success_url(self):
        return reverse_lazy("recipe-detail", kwargs={"pk": self.object.id})

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = self.get_form()
        if form.is_valid():
            print(form.cleaned_data)
            return self.form_valid(form)
        else:
            print(form.cleaned_data)
            return self.form_invalid(form)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.user = self.request.user
        comment.recipe = self.object
        comment.save()
        return super().form_valid(form)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['categories'] = Category.objects.all()
        recipe = self.object
        context["form"] = self.get_form()
        context['parent_comments'] = recipe.comments.filter(parent_comment__isnull=True)
        return context

from stories.tasks import dump_database
from django.http import HttpResponse

def dump(request):
    dump_database.delay()
    return HttpResponse('Database dump olunur!')


class SubscribeView(CreateView):
    form_class = SubscriberForm
    success_url = reverse_lazy('home')
    http_method_names = ('post',)

    def form_valid(self, *args, **kwargs):
        messages.success(self.request, 'Ugurla subscribe oldunuz her gun bilgilendirileceksiniz!')
        return super().form_valid(*args, **kwargs)
    
    def form_invalid(self, form):
        messages.error(self.request, 'Dogru email daxil edin!')
        return redirect(reverse_lazy('home'))


class UserProfile(LoginRequiredMixin, ListView):
    model = Recipe
    template_name = 'user-profile.html'


    def get_queryset(self):
        user = self.request.user
        queryset = super().get_queryset()
        return queryset.filter(author=user)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data()
        context['story_list'] = Story.objects.filter(author=self.request.user)
        return context




class CreateStory(LoginRequiredMixin, CreateView):
    form_class = StoryForm
    template_name = 'create_blog.html'
    success_url = '/'

    def form_valid(self, form):
        story = form.save(commit=False)
        story.author = self.request.user
        story.save()
        return super().form_valid(form)


class CreateRecipe(LoginRequiredMixin, CreateView):
    form_class = RecipeForm
    template_name = 'create_blog.html'

    def form_valid(self, form):
        story = form.save(commit=False)
        story.author = self.request.user
        story.save()
        return super().form_valid(form)


class RecipeUpdateView(LoginRequiredMixin, UpdateView):
    model = Recipe
    form_class = RecipeForm
    template_name = 'create_blog.html'


class RecipeDeleteView(LoginRequiredMixin, DeleteView):
    model = Recipe
    success_url = reverse_lazy('user-profile')


    # def form_valid(self, form):
    #     story = form.save(commit=False)
    #     story.author = self.request.user
    #     story.save()
    #     return super().form_valid(form)





# def recipe_detail(request):
#     return render(request, 'single.html')

# def contact(request):
#     if request.method == 'POST':
#         form = ContactForm(data=request.POST)
#         if form.is_valid():
#             print('ok-dir')
#             form.save()
#             messages.success(request, 'Mesajiniz Ugurla gonderildi!')
#             return redirect('/')
#     else:
#         form = ContactForm()
#     context = {
#         'form': form,
#     }
#     return render(request, 'contact.html', context)

class ContactView(CreateView):
    form_class = ContactForm
    template_name = 'contact.html'
    success_url = '/'

    def form_valid(self, *args, **kwargs):
        messages.success(self.request, 'Mesajiniz Ugurla gonderildi!')
        return super().form_valid(*args, **kwargs)




# def login(request):
#     form = LoginForm()
#     context = {
#         'form': form
#     }
#     return render(request, 'login.html', context)

food_stories/stories/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="hero-wrap hero-wrap-2" style="background-image: url('{% static 'images/bg_4.jpg' %}');">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">About Us</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>About us<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

{% include 'includes/about_section.html' %}


{% endblock %}

food_stories/stories/templates/create_blog.html
{% extends 'base.html' %} 

{% block content %}
    <section class="ftco-section contact-section create-story">
        <div class="container">
            <div class="row block-9 justify-content-center">
                <div class="col-md-6 order-md-last d-flex">
                    <form action="" method="POST" enctype="multipart/form-data" class="bg-light p-5 contact-form">
                        {{form.non_field_errors }}
                        <a class="navbar-brand center" href="#">Stories<span>.</span></a>
                        {% csrf_token %}
                        {% for field in form %}
                        <div class="form-group">
                            {{field}}
                            {{field.help_text}}
                            {{field.errors}}
                        </div>
                        {% endfor %}
                        <!-- <div class="form-group">
                            <input type="text" class="form-control" placeholder="Title">
                        </div>
                        <div class="form-group">
                            <textarea rows="10" class="form-control" placeholder="Description"></textarea>
                        </div>
                        <div class="form-group">
                            <select class="form-control" name="" id="">
                                    <option value="0">Select category</option>
                                    <option value="1">-----</option>
                                
                                </select>
                        </div>

                        <div class="form-group">
                            <input type="file">
                        </div> -->
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </section>

    {% endblock %}

food_stories/stories/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <form action="" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{form.username.label}}
            {{form.username}}
            {{form.username.help_text}}
            {{form.username.errors}}
        </div>

        <div class="form-group">
            {{form.password.label}}
            {{form.password}}
            {{form.password.errors}}
        </div>

        <input type="submit" value="Sign In">

    </form>
</div>
{% endblock %}

food_stories/stories/templates/single.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="hero-wrap hero-wrap-2" style="background-image: url({% static 'images/bg_4.jpg' %});">
    <div class="overlay"></div>
    <div class="container">
        <div class="row no-gutters slider-text align-items-end justify-content-center">
            <div class="col-md-9 ftco-animate pb-5 text-center">
                <h1 class="mb-3 bread">{{recipe.title}}</h1>
                <p class="breadcrumbs"><span class="mr-2"><a href="index.html">Home <i
                        class="ion-ios-arrow-forward"></i></a></span> <span>Article Single<i
                        class="ion-ios-arrow-forward"></i></span></p>
            </div>
        </div>
    </div>
</section>

<section class="ftco-section">
    <div class="container">
        <div class="row">
            
             <div class="col-lg-8 order-lg-last ftco-animate">
                 {{recipe.long_description|safe}}
               <!-- <h2 class="mb-3">It is a long established fact a reader be distracted</h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis, eius mollitia suscipit,
                    quisquam doloremque distinctio perferendis et doloribus unde architecto optio laboriosam porro
                    adipisci sapiente officiis nemo accusamus ad praesentium? Esse minima nisi et. Dolore perferendis,
                    enim praesentium omnis, iste doloremque quia officia optio deserunt molestiae voluptates soluta
                    architecto tempora.</p>
                <p>
                    <img src="{% static 'images/image_6.jpg' %}" alt="" class="img-fluid">
                </p>
                <p>Molestiae cupiditate inventore animi, maxime sapiente optio, illo est nemo veritatis repellat sunt
                    doloribus nesciunt! Minima laborum magni reiciendis qui voluptate quisquam voluptatem soluta illo
                    eum ullam incidunt rem assumenda eveniet eaque sequi deleniti tenetur dolore amet fugit perspiciatis
                    ipsa, odit. Nesciunt dolor minima esse vero ut ea, repudiandae suscipit!</p>
                <h2 class="mb-3 mt-5">#2. Creative WordPress Themes</h2>
                <p>Temporibus ad error suscipit exercitationem hic molestiae totam obcaecati rerum, eius aut, in.
                    Exercitationem atque quidem tempora maiores ex architecto voluptatum aut officia doloremque. Error
                    dolore voluptas, omnis molestias odio dignissimos culpa ex earum nisi consequatur quos odit quasi
                    repellat qui officiis reiciendis incidunt hic non? Debitis commodi aut, adipisci.</p>
                <p>
                    <img src="{% static 'images/image_4.jpg' %}" alt="" class="img-fluid">
                </p>
                <p>Quisquam esse aliquam fuga distinctio, quidem delectus veritatis reiciendis. Nihil explicabo quod,
                    est eos ipsum. Unde aut non tenetur tempore, nisi culpa voluptate maiores officiis quis vel ab
                    consectetur suscipit veritatis nulla quos quia aspernatur perferendis, libero sint. Error, velit,
                    porro. Deserunt minus, quibusdam iste enim veniam, modi rem maiores.</p>
                <p>Odit voluptatibus, eveniet vel nihil cum ullam dolores laborum, quo velit commodi rerum eum quidem
                    pariatur! Quia fuga iste tenetur, ipsa vel nisi in dolorum consequatur, veritatis porro explicabo
                    soluta commodi libero voluptatem similique id quidem? Blanditiis voluptates aperiam non magni.
                    Reprehenderit nobis odit inventore, quia laboriosam harum excepturi ea.</p>
                <p>Adipisci vero culpa, eius nobis soluta. Dolore, maxime ullam ipsam quidem, dolor distinctio similique
                    asperiores voluptas enim, exercitationem ratione aut adipisci modi quod quibusdam iusto, voluptates
                    beatae iure nemo itaque laborum. Consequuntur et pariatur totam fuga eligendi vero dolorum
                    provident. Voluptatibus, veritatis. Beatae numquam nam ab voluptatibus culpa, tenetur
                    recusandae!</p>
                <p>Voluptas dolores dignissimos dolorum temporibus, autem aliquam ducimus at officia adipisci quasi nemo
                    a perspiciatis provident magni laboriosam repudiandae iure iusto commodi debitis est blanditiis
                    alias laborum sint dolore. Dolores, iure, reprehenderit. Error provident, pariatur cupiditate soluta
                    doloremque aut ratione. Harum voluptates mollitia illo minus praesentium, rerum ipsa debitis,
                    inventore?</p> -->
                <div class="tag-widget post-tag-container mb-5 mt-5">
                    <div class="tagcloud">
                        <a href="#" class="tag-cloud-link">Life</a>
                        <a href="#" class="tag-cloud-link">Sport</a>
                        <a href="#" class="tag-cloud-link">Tech</a>
                        <a href="#" class="tag-cloud-link">Travel</a>
                    </div>
                </div>

                <div class="about-author d-flex p-4 bg-light">
                    <div class="bio mr-5">
                        <img src="{% static 'images/person_1.jpg' %}" alt="Image placeholder" class="img-fluid mb-4">
                    </div>
                    <div class="desc">
                        <h3>George Washington</h3>
                        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus itaque, autem
                            necessitatibus voluptate quod mollitia delectus aut, sunt placeat nam vero culpa sapiente
                            consectetur similique, inventore eos fugit cupiditate numquam!</p>
                    </div>
                </div>


                <div class="pt-5 mt-5">
                    <h3 class="mb-5">6 Comments</h3>
                    <ul class="comment-list">
                        {% for comment in parent_comments %}
                            {% include 'includes/comment.html' %}
                        {% endfor %}
                    </ul>
                    <!-- END comment-list -->
                    {% if request.user.is_authenticated %}
                    <div class="comment-form-wrap pt-5">
                        <h3 class="mb-5">Leave a comment</h3>

                        <form action="" id="comment-form" method="POST" class="p-5 bg-light">
                            {% csrf_token %}
                            <p id="replyto"></p>
                            {% for field in form.visible_fields %}
                            <div class="form-group">
                                <label for="message">{{field.label_tag}}</label>
                                {{field}}
                                {{field.hepl_text}}
                                {{field.errors}}
                            </div>
                            {% endfor %}

                            {% for field in form.hidden_fields %}
                                {{field}}
                            {% endfor %}

                            <div class="form-group">
                                <input type="submit" value="Post Comment" class="btn py-3 px-4 btn-primary">
                            </div>

                        </form>
                    </div>
                    {% endif %}
                </div>
            </div> <!-- .col-md-8 -->
            <div class="col-lg-4 sidebar pr-lg-5 ftco-animate">
                <div class="sidebar-box">
                    <form action="#" class="search-form">
                        <div class="form-group">
                            <span class="icon icon-search"></span>
                            <input type="text" class="form-control" placeholder="Type a keyword and hit enter">
                        </div>
                    </form>
                </div>
                <div class="sidebar-box ftco-animate">
                    <ul class="categories">
                        <h3 class="heading mb-4">Categories</h3>
                        {% for category in categories %}
                            <li><a href="{% url 'recipes' %}?category={{category.id}}">{{category.title}} <span>{{category.recipe_set.count}}</span></a></li>
                        {% endfor %}
                        <!-- <li><a href="#">Travel <span>(12)</span></a></li>
                        <li><a href="#">Tour <span>(22)</span></a></li>
                        <li><a href="#">Destination <span>(37)</span></a></li>
                        <li><a href="#">Drinks <span>(42)</span></a></li>
                        <li><a href="#">Foods <span>(14)</span></a></li>
                        <li><a href="#">Travel <span>(140)</span></a></li> -->
                    </ul>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Recent Blog</h3>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'images/image_1.jpg' %});"></a>
                        <div class="text">
                            <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'images/image_2.jpg' %});"></a>
                        <div class="text">
                            <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                    <div class="block-21 mb-4 d-flex">
                        <a class="blog-img mr-4" style="background-image: url({% static 'images/image_3.jpg' %});"></a>
                        <div class="text">
                            <h3><a href="#">Even the all-powerful Pointing has no control about the blind texts</a></h3>
                            <div class="meta">
                                <div><a href="#"><span class="icon-calendar"></span> February 12, 2019</a></div>
                                <div><a href="#"><span class="icon-person"></span> Admin</a></div>
                                <div><a href="#"><span class="icon-chat"></span> 19</a></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="sidebar-box ftco-animate">
                    <h3 class="heading mb-4">Tag Cloud</h3>
                    <div class="tagcloud">
                        <a href="#" class="tag-cloud-link">dish</a>
                        <a href="#" class="tag-cloud-link">menu</a>
                        <a href="#" class="tag-cloud-link">food</a>
                        <a href="#" class="tag-cloud-link">sweet</a>
                        <a href="#" class="tag-cloud-link">tasty</a>
                        <a href="#" class="tag-cloud-link">delicious</a>
                        <a href="#" class="tag-cloud-link">desserts</a>
                        <a href="#" class="tag-cloud-link">drinks</a>
                    </div>
                </div>
            </div>

        </div>
    </div>
</section> <!-- .section -->



{% endblock %}

{% block js %}

    <script>
        document.querySelectorAll('.reply').forEach(element => {
            element.addEventListener('click', function(){
                document.querySelector('#replyto').innerHTML = `Reply to: ${ element.getAttribute('data-user')} <span onclick="remove_reply();" >&times</span>`
                document.querySelector('#id_parent_comment').value = element.getAttribute('data-id');
            })
        });
        function remove_reply(){
            document.querySelector('#replyto').innerHTML = '';
            document.querySelector('#id_parent_comment').value = '';
        }
    </script>

{% endblock %}